# Generated by Django 5.0.7 on 2025-03-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='video',
        ),
    ]
