# Generated by Django 5.0.7 on 2025-03-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darry', '0002_remove_info_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='poster',
        ),
    ]
