# Generated by Django 5.0.7 on 2025-03-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darry', '0003_rename_info_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='poster',
        ),
    ]
