# Generated by Django 5.0.7 on 2025-03-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darry', '0004_info_product_delete_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
