# Generated by Django 5.0.7 on 2025-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darry', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
