# Generated by Django 5.0.7 on 2025-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darry', '0009_rename_comment_review_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
