# Generated by Django 5.0.7 on 2025-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darry', '0011_review_date_alter_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
